/**
 * 30 Unique Furniture Store Layouts
 * Each layout is designed to be visually distinct for multi-client SaaS
 * All themed around furniture retail with unique combinations
 */

export const FURNITURE_LAYOUTS = [
  // ===== MODERN (6) - Contemporary furniture stores =====
  {
    name: 'Modern Minimal',
    category: 'MODERN',
    premium: false,
    headerStyle: 'minimal-bar',
    heroStyle: 'split-image',
    productGrid: '3-col-cards',
    footerStyle: 'footer-minimal',
    primaryColor: '#0f172a',
    accentColor: '#6366f1',
    bgColor: '#ffffff',
    textColor: '#0f172a',
    fontHeading: 'Inter',
    fontBody: 'Inter',
    borderRadius: 8,
    animation: 'fade',
    cardStyle: 'shadow',
    spacing: 'normal',
    imageStyle: 'rounded',
    buttonStyle: 'solid',
    navPosition: 'top',
    description: 'Clean lines, generous whitespace, subtle motion. Perfect for Scandinavian furniture brands.',
  },
  {
    name: 'Urban Loft',
    category: 'MODERN',
    premium: false,
    headerStyle: 'sticky-glass',
    heroStyle: 'full-bleed',
    productGrid: 'masonry',
    footerStyle: 'footer-split',
    primaryColor: '#1c1917',
    accentColor: '#dc2626',
    bgColor: '#fafafa',
    textColor: '#1c1917',
    fontHeading: 'Archivo',
    fontBody: 'Inter',
    borderRadius: 2,
    animation: 'slide',
    cardStyle: 'border',
    spacing: 'compact',
    imageStyle: 'sharp',
    buttonStyle: 'outline',
    navPosition: 'sticky',
    description: 'Industrial vibes with exposed edges. For urban furniture & loft-style collections.',
  },
  {
    name: 'Tech Forward',
    category: 'MODERN',
    premium: true,
    headerStyle: 'split-nav',
    heroStyle: 'grid-cells',
    productGrid: '4-col-tight',
    footerStyle: 'footer-mega',
    primaryColor: '#020617',
    accentColor: '#22d3ee',
    bgColor: '#0f172a',
    textColor: '#e2e8f0',
    fontHeading: 'JetBrains Mono',
    fontBody: 'Inter',
    borderRadius: 0,
    animation: 'zoom',
    cardStyle: 'glass',
    spacing: 'minimal',
    imageStyle: 'square',
    buttonStyle: 'ghost',
    navPosition: 'side',
    description: 'Dark theme with neon accents. Smart furniture & tech-enabled home goods.',
  },
  {
    name: 'Nordic Breeze',
    category: 'MODERN',
    premium: false,
    headerStyle: 'centered-logo',
    heroStyle: 'carousel',
    productGrid: '3-col-cards',
    footerStyle: 'footer-center',
    primaryColor: '#3f6212',
    accentColor: '#e7e5e4',
    bgColor: '#f7f6f3',
    textColor: '#1c1917',
    fontHeading: 'DM Sans',
    fontBody: 'DM Sans',
    borderRadius: 16,
    animation: 'fade',
    cardStyle: 'flat',
    spacing: 'spacious',
    imageStyle: 'circle',
    buttonStyle: 'pill',
    navPosition: 'top',
    description: 'Soft beige, sage green, rounded everything. Hygge-focused furniture stores.',
  },
  {
    name: 'Metro Edge',
    category: 'MODERN',
    premium: true,
    headerStyle: 'minimal-bar',
    heroStyle: 'video-bg',
    productGrid: 'slider',
    footerStyle: 'footer-mega',
    primaryColor: '#18181b',
    accentColor: '#f97316',
    bgColor: '#ffffff',
    textColor: '#18181b',
    fontHeading: 'Space Grotesk',
    fontBody: 'Inter',
    borderRadius: 4,
    animation: 'slide',
    cardStyle: 'outlined',
    spacing: 'compact',
    imageStyle: 'rounded',
    buttonStyle: 'solid',
    navPosition: 'sticky',
    description: 'Bold typography with horizontal product sliders. High-end urban furniture.',
  },
  {
    name: 'Fresh Bloom',
    category: 'MODERN',
    premium: false,
    headerStyle: 'centered-logo',
    heroStyle: 'split-image',
    productGrid: 'bento',
    footerStyle: 'footer-minimal',
    primaryColor: '#15803d',
    accentColor: '#fb7185',
    bgColor: '#fefce8',
    textColor: '#1c1917',
    fontHeading: 'Plus Jakarta Sans',
    fontBody: 'Plus Jakarta Sans',
    borderRadius: 20,
    animation: 'fade',
    cardStyle: 'shadow',
    spacing: 'spacious',
    imageStyle: 'rounded',
    buttonStyle: 'pill',
    navPosition: 'top',
    description: 'Pastel yellow, leafy green, bento-grid layout. Playful modern furniture.',
  },

  // ===== LUXURY (6) - High-end furniture boutiques =====
  {
    name: 'Royal Elegance',
    category: 'LUXURY',
    premium: true,
    headerStyle: 'centered-logo',
    heroStyle: 'full-bleed',
    productGrid: 'list-rows',
    footerStyle: 'footer-mega',
    primaryColor: '#4c1d95',
    accentColor: '#d4af37',
    bgColor: '#0c0a09',
    textColor: '#fafaf9',
    fontHeading: 'Playfair Display',
    fontBody: 'Cormorant Garamond',
    borderRadius: 0,
    animation: 'fade',
    cardStyle: 'border',
    spacing: 'spacious',
    imageStyle: 'square',
    buttonStyle: 'outline',
    navPosition: 'top',
    description: 'Midnight backdrop with gold accents. Heirloom furniture & luxury antiques.',
  },
  {
    name: 'Velvet Night',
    category: 'LUXURY',
    premium: true,
    headerStyle: 'split-nav',
    heroStyle: 'carousel',
    productGrid: 'list-rows',
    footerStyle: 'footer-center',
    primaryColor: '#581c87',
    accentColor: '#e879f9',
    bgColor: '#1e1b29',
    textColor: '#f5e9ff',
    fontHeading: 'Cormorant Garamond',
    fontBody: 'Inter',
    borderRadius: 12,
    animation: 'zoom',
    cardStyle: 'glass',
    spacing: 'normal',
    imageStyle: 'rounded',
    buttonStyle: 'solid',
    navPosition: 'top',
    description: 'Deep plum with violet shimmer. Romantic evening furniture collections.',
  },
  {
    name: 'Marble & Gold',
    category: 'LUXURY',
    premium: true,
    headerStyle: 'centered-logo',
    heroStyle: 'split-image',
    productGrid: '3-col-cards',
    footerStyle: 'footer-mega',
    primaryColor: '#1c1917',
    accentColor: '#c4a253',
    bgColor: '#f5f3ef',
    textColor: '#1c1917',
    fontHeading: 'Playfair Display',
    fontBody: 'Lato',
    borderRadius: 0,
    animation: 'fade',
    cardStyle: 'outlined',
    spacing: 'spacious',
    imageStyle: 'sharp',
    buttonStyle: 'outline',
    navPosition: 'top',
    description: 'Cream marble with brushed gold. Luxury showroom aesthetic.',
  },
  {
    name: 'Platinum Suite',
    category: 'LUXURY',
    premium: true,
    headerStyle: 'split-nav',
    heroStyle: 'grid-cells',
    productGrid: '4-col-tight',
    footerStyle: 'footer-split',
    primaryColor: '#334155',
    accentColor: '#94a3b8',
    bgColor: '#f1f5f9',
    textColor: '#0f172a',
    fontHeading: 'Cormorant Garamond',
    fontBody: 'Inter',
    borderRadius: 2,
    animation: 'slide',
    cardStyle: 'shadow',
    spacing: 'minimal',
    imageStyle: 'square',
    buttonStyle: 'ghost',
    navPosition: 'sticky',
    description: 'Platinum-grey minimalism. Exclusive designer furniture boutique.',
  },
  {
    name: 'Diamond Collection',
    category: 'LUXURY',
    premium: true,
    headerStyle: 'sticky-glass',
    heroStyle: 'video-bg',
    productGrid: 'slider',
    footerStyle: 'footer-mega',
    primaryColor: '#0f172a',
    accentColor: '#67e8f9',
    bgColor: '#ffffff',
    textColor: '#0f172a',
    fontHeading: 'Playfair Display',
    fontBody: 'Inter',
    borderRadius: 8,
    animation: 'zoom',
    cardStyle: 'glass',
    spacing: 'normal',
    imageStyle: 'circle',
    buttonStyle: 'pill',
    navPosition: 'sticky',
    description: 'Ice-blue accents over B&W. Crystal-clear luxury furniture.',
  },
  {
    name: 'Timeless Classic',
    category: 'LUXURY',
    premium: false,
    headerStyle: 'minimal-bar',
    heroStyle: 'full-bleed',
    productGrid: '3-col-cards',
    footerStyle: 'footer-center',
    primaryColor: '#451a03',
    accentColor: '#a16207',
    bgColor: '#faf6f0',
    textColor: '#451a03',
    fontHeading: 'Playfair Display',
    fontBody: 'Lora',
    borderRadius: 6,
    animation: 'fade',
    cardStyle: 'border',
    spacing: 'spacious',
    imageStyle: 'rounded',
    buttonStyle: 'outline',
    navPosition: 'top',
    description: 'Warm sepia tones with serif elegance. Heritage furniture stores.',
  },

  // ===== MINIMAL (6) - Clean, simple furniture shops =====
  {
    name: 'Pure White',
    category: 'MINIMAL',
    premium: false,
    headerStyle: 'minimal-bar',
    heroStyle: 'split-image',
    productGrid: '3-col-cards',
    footerStyle: 'footer-minimal',
    primaryColor: '#000000',
    accentColor: '#000000',
    bgColor: '#ffffff',
    textColor: '#000000',
    fontHeading: 'Inter',
    fontBody: 'Inter',
    borderRadius: 0,
    animation: 'none',
    cardStyle: 'flat',
    spacing: 'spacious',
    imageStyle: 'square',
    buttonStyle: 'outline',
    navPosition: 'top',
    description: 'Pure black on white. The ultimate less-is-more furniture catalog.',
  },
  {
    name: 'Zen Garden',
    category: 'MINIMAL',
    premium: false,
    headerStyle: 'centered-logo',
    heroStyle: 'carousel',
    productGrid: 'list-rows',
    footerStyle: 'footer-center',
    primaryColor: '#52525b',
    accentColor: '#84cc16',
    bgColor: '#fafaf7',
    textColor: '#27272a',
    fontHeading: 'Noto Serif JP',
    fontBody: 'Inter',
    borderRadius: 16,
    animation: 'fade',
    cardStyle: 'shadow',
    spacing: 'spacious',
    imageStyle: 'circle',
    buttonStyle: 'pill',
    navPosition: 'top',
    description: 'Off-white stones with mossy green. Japanese-inspired furniture.',
  },
  {
    name: 'Swiss Style',
    category: 'MINIMAL',
    premium: true,
    headerStyle: 'split-nav',
    heroStyle: 'grid-cells',
    productGrid: 'bento',
    footerStyle: 'footer-mega',
    primaryColor: '#dc2626',
    accentColor: '#000000',
    bgColor: '#ffffff',
    textColor: '#000000',
    fontHeading: 'Space Grotesk',
    fontBody: 'Inter',
    borderRadius: 0,
    animation: 'slide',
    cardStyle: 'outlined',
    spacing: 'minimal',
    imageStyle: 'sharp',
    buttonStyle: 'solid',
    navPosition: 'side',
    description: 'Red + black grid system. Brutally precise furniture catalog.',
  },
  {
    name: 'Mono Chrome',
    category: 'MINIMAL',
    premium: false,
    headerStyle: 'minimal-bar',
    heroStyle: 'split-image',
    productGrid: '4-col-tight',
    footerStyle: 'footer-minimal',
    primaryColor: '#1f2937',
    accentColor: '#6b7280',
    bgColor: '#f9fafb',
    textColor: '#1f2937',
    fontHeading: 'Inter',
    fontBody: 'Inter',
    borderRadius: 4,
    animation: 'fade',
    cardStyle: 'border',
    spacing: 'compact',
    imageStyle: 'rounded',
    buttonStyle: 'ghost',
    navPosition: 'sticky',
    description: 'Pure grayscale. Sophisticated neutral furniture collections.',
  },
  {
    name: 'Breathing Space',
    category: 'MINIMAL',
    premium: false,
    headerStyle: 'centered-logo',
    heroStyle: 'full-bleed',
    productGrid: 'list-rows',
    footerStyle: 'footer-center',
    primaryColor: '#0f766e',
    accentColor: '#0f766e',
    bgColor: '#ffffff',
    textColor: '#0f172a',
    fontHeading: 'Fraunces',
    fontBody: 'Inter',
    borderRadius: 20,
    animation: 'fade',
    cardStyle: 'shadow',
    spacing: 'spacious',
    imageStyle: 'rounded',
    buttonStyle: 'pill',
    navPosition: 'top',
    description: 'Extra-large spacing with single teal accent. Breathable furniture catalog.',
  },
  {
    name: 'Outline',
    category: 'MINIMAL',
    premium: true,
    headerStyle: 'split-nav',
    heroStyle: 'grid-cells',
    productGrid: 'masonry',
    footerStyle: 'footer-minimal',
    primaryColor: '#000000',
    accentColor: '#000000',
    bgColor: '#ffffff',
    textColor: '#000000',
    fontHeading: 'Inter',
    fontBody: 'Inter',
    borderRadius: 0,
    animation: 'none',
    cardStyle: 'outlined',
    spacing: 'normal',
    imageStyle: 'square',
    buttonStyle: 'outline',
    navPosition: 'top',
    description: 'Everything outlined, no fills. Architectural furniture showcase.',
  },

  // ===== CREATIVE (6) - Artistic & bold furniture stores =====
  {
    name: 'Bold Statements',
    category: 'CREATIVE',
    premium: true,
    headerStyle: 'sticky-glass',
    heroStyle: 'video-bg',
    productGrid: 'masonry',
    footerStyle: 'footer-mega',
    primaryColor: '#7c3aed',
    accentColor: '#facc15',
    bgColor: '#0b0b14',
    textColor: '#fafafa',
    fontHeading: 'Archivo Black',
    fontBody: 'Inter',
    borderRadius: 0,
    animation: 'zoom',
    cardStyle: 'glass',
    spacing: 'compact',
    imageStyle: 'sharp',
    buttonStyle: 'solid',
    navPosition: 'sticky',
    description: 'Neon yellow over deep violet. Statement furniture pieces.',
  },
  {
    name: 'Art Gallery',
    category: 'CREATIVE',
    premium: true,
    headerStyle: 'centered-logo',
    heroStyle: 'carousel',
    productGrid: 'list-rows',
    footerStyle: 'footer-center',
    primaryColor: '#1c1917',
    accentColor: '#ea580c',
    bgColor: '#fef3e2',
    textColor: '#1c1917',
    fontHeading: 'Fraunces',
    fontBody: 'Inter',
    borderRadius: 0,
    animation: 'fade',
    cardStyle: 'flat',
    spacing: 'spacious',
    imageStyle: 'square',
    buttonStyle: 'outline',
    navPosition: 'top',
    description: 'Cream paper with orange accents. Treats furniture like exhibits.',
  },
  {
    name: 'Magazine Editorial',
    category: 'CREATIVE',
    premium: true,
    headerStyle: 'split-nav',
    heroStyle: 'grid-cells',
    productGrid: 'bento',
    footerStyle: 'footer-split',
    primaryColor: '#111827',
    accentColor: '#db2777',
    bgColor: '#ffffff',
    textColor: '#111827',
    fontHeading: 'Playfair Display',
    fontBody: 'Lora',
    borderRadius: 2,
    animation: 'slide',
    cardStyle: 'border',
    spacing: 'normal',
    imageStyle: 'rounded',
    buttonStyle: 'ghost',
    navPosition: 'side',
    description: 'Editorial columns with pink drop-caps. Magazine-style furniture catalog.',
  },
  {
    name: 'Retro Wave',
    category: 'CREATIVE',
    premium: false,
    headerStyle: 'minimal-bar',
    heroStyle: 'full-bleed',
    productGrid: 'slider',
    footerStyle: 'footer-minimal',
    primaryColor: '#be185d',
    accentColor: '#0ea5e9',
    bgColor: '#0f172a',
    textColor: '#fbcfe8',
    fontHeading: 'VT323',
    fontBody: 'Inter',
    borderRadius: 12,
    animation: 'zoom',
    cardStyle: 'glass',
    spacing: 'compact',
    imageStyle: 'circle',
    buttonStyle: 'pill',
    navPosition: 'sticky',
    description: '80s synthwave aesthetic. Playful vintage furniture collections.',
  },
  {
    name: 'Brutalist',
    category: 'CREATIVE',
    premium: false,
    headerStyle: 'split-nav',
    heroStyle: 'split-image',
    productGrid: '4-col-tight',
    footerStyle: 'footer-mega',
    primaryColor: '#000000',
    accentColor: '#84cc16',
    bgColor: '#d4d4d4',
    textColor: '#000000',
    fontHeading: 'Space Mono',
    fontBody: 'Space Mono',
    borderRadius: 0,
    animation: 'none',
    cardStyle: 'outlined',
    spacing: 'minimal',
    imageStyle: 'sharp',
    buttonStyle: 'outline',
    navPosition: 'top',
    description: 'Concrete background with lime accents. Intentionally raw furniture.',
  },
  {
    name: 'Collage',
    category: 'CREATIVE',
    premium: true,
    headerStyle: 'centered-logo',
    heroStyle: 'carousel',
    productGrid: 'masonry',
    footerStyle: 'footer-center',
    primaryColor: '#c2410c',
    accentColor: '#0891b2',
    bgColor: '#fff8e7',
    textColor: '#1c1917',
    fontHeading: 'Caveat',
    fontBody: 'Inter',
    borderRadius: 24,
    animation: 'slide',
    cardStyle: 'shadow',
    spacing: 'spacious',
    imageStyle: 'rounded',
    buttonStyle: 'pill',
    navPosition: 'top',
    description: 'Hand-written headings with scrapbook energy. Personal furniture curation.',
  },

  // ===== CLASSIC (6) - Traditional furniture stores =====
  {
    name: 'Heritage Oak',
    category: 'CLASSIC',
    premium: false,
    headerStyle: 'minimal-bar',
    heroStyle: 'split-image',
    productGrid: '3-col-cards',
    footerStyle: 'footer-mega',
    primaryColor: '#78350f',
    accentColor: '#a16207',
    bgColor: '#faf6ef',
    textColor: '#1c1917',
    fontHeading: 'Merriweather',
    fontBody: 'Lora',
    borderRadius: 6,
    animation: 'fade',
    cardStyle: 'shadow',
    spacing: 'normal',
    imageStyle: 'rounded',
    buttonStyle: 'solid',
    navPosition: 'top',
    description: 'Warm oak tones with serif typography. Trustworthy wood furniture.',
  },
  {
    name: 'Victorian Grace',
    category: 'CLASSIC',
    premium: true,
    headerStyle: 'centered-logo',
    heroStyle: 'carousel',
    productGrid: 'list-rows',
    footerStyle: 'footer-split',
    primaryColor: '#4a044e',
    accentColor: '#b45309',
    bgColor: '#fdf6e3',
    textColor: '#1c1917',
    fontHeading: 'Cormorant Garamond',
    fontBody: 'Lora',
    borderRadius: 4,
    animation: 'fade',
    cardStyle: 'border',
    spacing: 'spacious',
    imageStyle: 'square',
    buttonStyle: 'outline',
    navPosition: 'top',
    description: 'Aged paper with plum + brass. Antique furniture collections.',
  },
  {
    name: 'Coastal Breeze',
    category: 'CLASSIC',
    premium: false,
    headerStyle: 'minimal-bar',
    heroStyle: 'full-bleed',
    productGrid: '3-col-cards',
    footerStyle: 'footer-center',
    primaryColor: '#075985',
    accentColor: '#fbbf24',
    bgColor: '#eff6ff',
    textColor: '#0c4a6e',
    fontHeading: 'Lora',
    fontBody: 'Inter',
    borderRadius: 16,
    animation: 'fade',
    cardStyle: 'flat',
    spacing: 'normal',
    imageStyle: 'circle',
    buttonStyle: 'pill',
    navPosition: 'top',
    description: 'Sky-blue with sandy gold. Beach-house furniture catalog.',
  },
  {
    name: 'Farmhouse Charm',
    category: 'CLASSIC',
    premium: false,
    headerStyle: 'centered-logo',
    heroStyle: 'split-image',
    productGrid: 'bento',
    footerStyle: 'footer-mega',
    primaryColor: '#7c2d12',
    accentColor: '#65a30d',
    bgColor: '#fef9e7',
    textColor: '#1c1917',
    fontHeading: 'Lora',
    fontBody: 'Lora',
    borderRadius: 12,
    animation: 'fade',
    cardStyle: 'shadow',
    spacing: 'spacious',
    imageStyle: 'rounded',
    buttonStyle: 'solid',
    navPosition: 'top',
    description: 'Buttercream + barn red + leafy green. Country furniture store.',
  },
  {
    name: 'Mediterranean Villa',
    category: 'CLASSIC',
    premium: true,
    headerStyle: 'split-nav',
    heroStyle: 'grid-cells',
    productGrid: '4-col-tight',
    footerStyle: 'footer-split',
    primaryColor: '#1e3a8a',
    accentColor: '#c2410c',
    bgColor: '#fef9f5',
    textColor: '#1c1917',
    fontHeading: 'Playfair Display',
    fontBody: 'Lora',
    borderRadius: 8,
    animation: 'slide',
    cardStyle: 'outlined',
    spacing: 'compact',
    imageStyle: 'sharp',
    buttonStyle: 'outline',
    navPosition: 'sticky',
    description: 'Terracotta + navy over stucco cream. Riviera-style furniture.',
  },
  {
    name: 'English Garden',
    category: 'CLASSIC',
    premium: false,
    headerStyle: 'minimal-bar',
    heroStyle: 'carousel',
    productGrid: 'masonry',
    footerStyle: 'footer-center',
    primaryColor: '#14532d',
    accentColor: '#be185d',
    bgColor: '#f7faf3',
    textColor: '#14532d',
    fontHeading: 'Lora',
    fontBody: 'Inter',
    borderRadius: 8,
    animation: 'fade',
    cardStyle: 'border',
    spacing: 'spacious',
    imageStyle: 'rounded',
    buttonStyle: 'pill',
    navPosition: 'top',
    description: 'Garden green with rose accents. Botanical furniture collections.',
  },
]
